USE [Barangay];
GO

SET QUOTED_IDENTIFIER ON;
GO

PRINT '=== Verifying All Required Columns ===';
PRINT '';

-- Check Appointments table
PRINT 'Appointments Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Appointments' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'VitalSigns Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'VitalSigns' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'StaffMembers Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'StaffMembers' 
ORDER BY ORDINAL_POSITION;

GO
