-- Fix all remaining NCDRiskAssessments fields to NVARCHAR(4000) for encryption support
-- This script updates all fields that are smaller than 4000 characters

-- Personal Information Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN HealthFacility NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN FamilyNo NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Address NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Barangay NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Telepono NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Kasarian NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Relihiyon NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CivilStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN FirstName NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN MiddleName NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN LastName NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Occupation NVARCHAR(4000) NULL;

-- Medical Information Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN CancerType NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CancerMedication NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CancerYear NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN DiabetesMedication NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN DiabetesYear NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN HypertensionMedication NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN HypertensionYear NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN LungDiseaseMedication NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN LungDiseaseYear NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN COPDYear NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CancerSite NVARCHAR(4000) NULL;

-- Lifestyle and Health Status Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN SmokingStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN AlcoholFrequency NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN AlcoholConsumption NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN ExerciseDuration NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN RiskStatus NVARCHAR(4000) NULL;

-- Chest Pain and Other Medical Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN ChestPain NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN ChestPainLocation NVARCHAR(4000) NULL;

-- Appointment and Assessment Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN AppointmentType NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN AssessmentDate NVARCHAR(4000) NULL;

-- Family History Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN FamilyHistoryOther NVARCHAR(4000) NULL;

-- Measurement Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN BMI NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN BMIStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN BPStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN BaselineBP NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN BloodSugarStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CancerScreeningStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CholesterolResult NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN CholesterolStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN FastingBloodSugar NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Height NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Hip NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN IDNumber NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN LeftArmMeanBP NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN RandomBloodSugar NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN RightArmMeanBP NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN RiskPercentage NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN UrineKetones NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN UrineProtein NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN WHRatio NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN WHStatus NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Waist NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN Weight NVARCHAR(4000) NULL;

-- Other Fields
ALTER TABLE NCDRiskAssessments ALTER COLUMN Designation NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN DoctorName NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN InterviewedBy NVARCHAR(4000) NULL;
ALTER TABLE NCDRiskAssessments ALTER COLUMN PatientSignature NVARCHAR(4000) NULL;

PRINT 'All NCDRiskAssessments fields updated to NVARCHAR(4000) for encryption support.';
